version: "3.3"

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: centraldb
    volumes:
      - ./init-table.sql:/docker-entrypoint-initdb.d/init-table.sql
      - ./db:/var/lib/postgresql/data


  solrdb:
    image: solr
    restart: always
    ports:
      - "8983:8983"
    entrypoint:
      - bash
      - "-c"
      - "precreate-core mentions; precreate-core resources; exec solr -f"
    volumes:
      - ./solrdb:/var/lib/solr/data


  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"


  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_EXTERNAL://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_EXTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper


  crawler:
    build:
      context: crawler/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - kafka


  api:
    build:
      context: api/
      dockerfile: Dockerfile
    restart: always
    ports:
        - "8080:8080"
    depends_on:
      - solrdb
      - db
    environment:
      WAIT_HOSTS: db:5432


  mentions-matcher:
    build:
      context: mentions-matcher/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - kafka
      - solrdb
      - db


  mentions-storage:
    build:
      context: mentions-storage/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - solrdb
      - db


  resource-filterer:
    build:
      context: resource-filterer/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - solrdb
      - kafka




